#!/bin/bash

# Bootstrap script for icm-development docker image #
#####################################################
# * Creates directory structure on mounted volumes
# * Installs MySQL databases
# * etc

BOOTSTRAP_DATA_DIR=/data/bootstrap/data
BASEDIR_DB=/data/db
BASEDIR_LOG=/data/log
BASEDIR_SRC=/data/www/icheckmovies

# Create log directory structure
echo "Creating log directories..."
for pkg in grunt mysql nginx php redis sphinx supervisor; do
    if [ ! -d $BASEDIR_LOG/$pkg ]; then
        echo "+ $pkg"
        mkdir -p $BASEDIR_LOG/$pkg
    fi
done

# Create database directory structure
echo "Creating database directories..."
for db in mysql redis sphinx; do
    if [ ! -d $BASEDIR_DB/$db ]; then
        echo "+ $db"
        mkdir -p $BASEDIR_DB/$db
    fi
done

echo "Setting directory permissions..."
chmod -R a+rx $BASEDIR_LOG
chown -R mysql:mysql $BASEDIR_DB/mysql
chown -R apache $BASEDIR_LOG/php
chown -R sphinx $BASEDIR_LOG/sphinx $BASEDIR_DB/sphinx

if [ ! -d $BASEDIR_DB/mysql/mysql ]; then
    echo "Installing MySQL databases..."
    /usr/bin/mysql_install_db --user=mysql &> /data/bootstrap/bootstrap.log
fi

echo "Populating MySQL databases..."
/etc/init.d/mysqld start &> /data/bootstrap/bootstrap.log
for sql in $BOOTSTRAP_DATA_DIR/*.sql; do
    echo "+ importing $sql"
    cat $sql | mysql
done

echo "Configuring Sphinx..."
ln -sf /data/www/icheckmovies/application/configuration/sphinx.conf /etc/sphinx/sphinx.conf

echo "Populating Sphinx search index..."
su - sphinx -c "indexer --all" &> /data/bootstrap/bootstrap.log
/etc/init.d/mysqld stop &> /data/bootstrap/bootstrap.log

echo "Creating iCheckMovies project structure and configuration..."
if [ ! -d $BASEDIR_SRC/etc ]; then mkdir -p $BASEDIR_SRC/etc; fi
if [ ! -d $BASEDIR_SRC/var ]; then mkdir -p $BASEDIR_SRC/var/{cache,smarty_compiled}; fi

cp -f $BOOTSTRAP_DATA_DIR/icm-local.conf $BASEDIR_SRC/etc/local.conf
cp -f $BOOTSTRAP_DATA_DIR/icm-mysql.conf $BASEDIR_SRC/etc/mysql.conf

sed -i "s/{LOCAL_HTTP_PORT}/${EXPORT_HTTP_PORT}/" $BASEDIR_SRC/etc/local.conf














