#!/bin/bash

# Bootstrap script for icm-development docker image #
#####################################################
# * Creates directory structure on mounted volumes
# * Installs MySQL databases
# * etc

if [ -z $1 ]; then
	echo "Usage: $0 <type>"
	exit 1
fi

TYPE=$1
BOOTSTRAP_DIR=/data/www/bootstrap

echo "Searching for bootstrap scripts..."
if [ -x $BOOTSTRAP_DIR/bootstrap ]; then
	echo "Running bootstrap scripts..."
	$BOOTSTRAP_DIR/bootstrap $TYPE

	if [ $? != 0 ]; then
		echo "Error running bootstrap scripts"
		exit 1
	fi
fi

echo "Starting supervisord..."
/usr/bin/supervisord --configuration=/etc/supervisord.conf
